### ISSUE TITLE
Not able to run mod1 pipeline.

### ISSUE THREAD

**Issue by ismail-temiz** [rseroter/pluralsight-concourse-dotnetcore#2]
Hi, I have just started learning concourse on Pluralsight.

I am on the first demo where we set up our first pipeline with the following YAML file:

```
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/rseroter/pluralsight-concourse-dotnetcore.git
    branch: master
    
    
jobs:
  - name: compile-app
    plan:
    - get: source-code
    - task: first-task
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: mcr.microsoft.com/dotnet/core/sdk
            tag: 2.2
        inputs:
        - name: source-code
        run:
            path: sh
            args:
            - -exec
            - |
              dotnet build ./source-code/pluralsight-concourse-dotnetcore.csproj
  - name: inspect-app
    plan:
    - get: source-code
      passed: [compile-app]
      trigger: true
    - task: first-task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        inputs:
        - name: source-code
        run:
            path: find
            args: [.]
```

I  am able to create the pipeline with `fly -t ps set-pipeline -c mod1-pipeline.yml -p mod1-pipeline` no problem. However when I try to run the pipeline `compile-app` job fails with 

```
selected worker: d9f010052786

Cloning into '/tmp/build/get'...

fatal: detected dubious ownership in repository at '/tmp/build/get'

To add an exception for this directory, call:


	git config --global --add safe.directory /tmp/build/get
```
Haven't been able to find a solution for this, any suggestions?

I am using MAC with Apple M1 Pro chip
